### ISSUE TITLE
CouchPotato Stuck on login screen / no sabnzbd

### ISSUE THREAD

**Issue by rjcogin** [jknight2014/knightcinema#2]
Last night i used the script on Ubuntu Server 14.04. The installation process was very nice but i ran into a couple of issues with the installed services. 

Sonarr - works perfectly.

CouchPotato - web interface loads to the login screen but i enter my login and the empty login screen just loads again. I can't seem to get past this point. I know my username and password is correct because i was able to log into sonarr with now problems.

Sabnzbd - the web interface won't load. is \\ip\sabnzbd the correct path? I even tried the port (8080) instead of the easy to remember url but it just takes me to a page with a html folder. when i click on this it take me to the Apache page.

**Comment by jknight2014** [comment]
Start by restarting the server. sudo shutdown -r now

sabNZBd runs on port 8085 so it does not conflict with Kodi. So try that port. Couchpotato has given me issues in the past. Seems off and on. Try accessing it by its port also and see if you can login. 

If they don't work By port check /var/log/upstart for logs of each.

**Comment by rjcogin** [comment]
thanks for your help i really appreciate it.

Sabnzbd works by port. yay.

But still have the same problem with couchpotato.
I was thinking i could reset the username and password in "settings.conf".
Where is couchpotato installed? i cant seem to find it anywhere.

**Comment by jknight2014** [comment]
Couchpotato is installed at ~/IPVR/.couchpotato. The settings are in settings.conf. Make sure to stop CP before you open the file. `sudo stop couchpotato`. You can type a plain password in the settings file but it will be hashed when CP starts. 

Once your done editing just use `sudo start couchpotato` to start it again. 

If you want read this guide for a more up to date easy urls. http://knightcinema.com/2015/09/05/super-easy-to-remember-home-urls/

**Comment by rjcogin** [comment]
That's great. I am able to access couchpotato now.
Thank you very much for your help.

**Comment by jknight2014** [comment]
Im glad it worked out. I have to find out what happens with the CP config file. That only happens sometimes.
